[setup]
pkgs = ["nodejs_22", "python311", "python311Packages.pip"]

[install]
cmds = [
  "rm -f package-lock.json",
  "npm install --legacy-peer-deps",
  "python3 -m pip install -r requirements.txt",
  "which python3 > .python_path && echo 'Python path guardado:' && cat .python_path"
]

[start]
cmd = "sh start.sh"
